# Generated by Django 4.2.2 on 2023-06-07 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="state",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state_name", models.CharField(max_length=50)),
                ("state_abbr", models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name="county",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("county_name", models.CharField(max_length=50)),
                (
                    "state_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="average_outdoors_admin.state",
                    ),
                ),
            ],
        ),
    ]
