# Generated by Django 4.2.2 on 2023-06-13 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("average_outdoors_admin", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="county",
            name="state_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="average_outdoors_admin.state",
            ),
        ),
        migrations.AlterField(
            model_name="state",
            name="state_name",
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
