# Generated by Django 4.2.2 on 2023-06-26 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("average_outdoors_admin", "0002_alter_county_state_id_alter_state_state_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="pagetypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="pages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_url", models.URLField()),
                (
                    "page_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="average_outdoors_api.pagetypes",
                    ),
                ),
                (
                    "state_reltn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="average_outdoors_admin.state",
                    ),
                ),
            ],
        ),
    ]
