# Generated by Django 4.2.2 on 2023-06-26 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("average_outdoors_admin", "0002_alter_county_state_id_alter_state_state_name"),
        ("average_outdoors_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="pages",
            new_name="page",
        ),
        migrations.RenameModel(
            old_name="pagetypes",
            new_name="pagetype",
        ),
    ]
