# Generated by Django 4.2.2 on 2023-06-26 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("average_outdoors_api", "0002_rename_pages_page_rename_pagetypes_pagetype"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagetype",
            name="page_type",
            field=models.CharField(
                choices=[(1, "Hunting"), (2, "Fishing"), (3, "Conservation")],
                default=1,
                max_length=25,
            ),
            preserve_default=False,
        ),
    ]
