# Generated by Django 4.2.2 on 2023-06-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("average_outdoors_api", "0003_pagetype_page_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="page_type",
            field=models.CharField(
                choices=[(1, "Hunting"), (2, "Fishing"), (3, "Conservation")],
                max_length=25,
            ),
        ),
        migrations.DeleteModel(
            name="pagetype",
        ),
    ]
