# Generated by Django 4.2.2 on 2023-06-26 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("average_outdoors_api", "0005_activities_alter_page_page_type"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="activities",
            new_name="activity",
        ),
    ]
