# Generated by Django 4.2.2 on 2023-06-26 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("average_outdoors_api", "0006_rename_activities_activity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="page",
            old_name="page_type",
            new_name="activity_reltn",
        ),
    ]
